# Generated by Django 3.2.3 on 2021-05-28 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('availability', models.BooleanField(default=False)),
                ('daytime', picklefield.fields.PickledObjectField(default={}, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('category', models.CharField(choices=[('General Education Courses', 'General Education Courses'), ('Professional Courses', 'Professional Courses')], default='Professional Courses', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='class_schedule', serialize=False, to='ssapp.course')),
                ('availability', models.BooleanField(default=False)),
                ('daytime', picklefield.fields.PickledObjectField(default={}, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_credits', models.PositiveSmallIntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='curriculum', to='ssapp.Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssapp.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ManyToManyField(blank=True, related_name='courses', to='ssapp.Faculty'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_credits', models.PositiveSmallIntegerField(default=0)),
                ('completed_course', models.ManyToManyField(blank=True, related_name='completed_courses', to='ssapp.Course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='ssapp.curriculum')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('enrolled_class', models.ManyToManyField(blank=True, related_name='enrolled_class', to='ssapp.ClassSchedule')),
            ],
        ),
    ]
